# docker-compose
version: '3.7'

services:
  app:
    build: .
    command: "bash -c 'npm install && npm start'"
    ports:
      - 4200:4200
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app